consultoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
	path('contacto/',views.mostrarContacto ,name="mostrarContacto"),
    path('asesores/<int:id_region>/',views.mostrarAsesores ,name="mostrarAsesores"),
    path('asesor/<int:id>/',views.mostrarAsesor ,name="mostrarAsesor"),
    path('index/',views.mostrarIndex ,name="mostrarIndex"),
    path('nosotros/',views.mostrarNosotros ,name="mostrarNosotros"),
    path('servicios/',views.mostrarServicios ,name="mostrarServicios"),
    path('pago/<int:id>/',views.mostrarPago ,name="mostrarPago"),
    path('asesor/registrar/',views.registrarAsesor ,name="registrarAsesor"),
    path('region/registrar/',views.registrarRegion ,name="registrarRegion"),
    path('contrata/listar/',views.listarContrata ,name="listarContrata"),

    #API
    path('api/asesor/registrar/',views.registarAsesorAPI ,name="registrarAsesorAPI"),
    path('api/region/registrar/',views.registarRegionAPI ,name="registrarRegionAPI"),
    path('api/contrata/registrar/<int:id>/',views.registrarContrataAPI ,name="registrarContrataAPI"),

]

main/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    nombre = models.CharField(max_length=40)
    activo = models.BooleanField(default=True)

class Asesor(models.Model):
    nombre = models.CharField(max_length=100)
    tipo_documento = models.CharField(max_length=20)
    documento = models.CharField(max_length=11)
    telefono = models.CharField(max_length=9)
    correo = models.CharField(max_length=50, null=True)
    funcion = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=19, decimal_places=2)
    foto = models.ImageField(blank=True, upload_to='asesor/')
    region = models.ForeignKey(Region, on_delete=models.PROTECT)

class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=9)
    direccion = models.CharField(max_length=100) 

class Contrata(models.Model):
    asunto = models.CharField(max_length=200)
    fecha = models.DateTimeField(auto_now_add=True)
    asesor = models.ForeignKey(Asesor, on_delete=models.PROTECT)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)

main/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
import json
from django.shortcuts import redirect

from .models import Region, Asesor, Cliente, Contrata



# Create your views here.
def mostrarContacto(request):
    context = {}
    return render(request,'main/contacto/contacto.html',context)

def mostrarAsesores(request, id_region):
    asesores = Asesor.objects.filter(region = id_region)
    regiones = Region.objects.filter(activo=True)
    context = {'asesores':asesores,'regiones':regiones,"oRegion":id_region,}
    return render(request,'main/asesores/asesores.html',context)

def mostrarAsesor(request, id):
    asesor = Asesor.objects.get(id= id )
    context = {'asesor':asesor,}
    return render(request,'main/asesor/asesor.html',context)

def mostrarIndex(request):
    context = {}
    return render(request,'main/index/index.html',context)

def mostrarNosotros(request):
    context = {}
    return render(request,'main/nosotros/nosotros.html',context)

def mostrarServicios(request):
    context = {}
    return render(request,'main/servicios/servicios.html',context)

def mostrarPago(request, id):
    asesor = Asesor.objects.get(id= id )
    context = {'asesor':asesor,}
    return render(request,'pago/pago.html',context)


def registrarAsesor(request):
    regiones = Region.objects.filter(activo=True)
    context = {'regiones':regiones,}
    return render(request,'asesor/registrar.html',context)

def registrarRegion(request):
    context = {}
    return render(request,'region/registrar.html',context)

def listarContrata(request):
    contratas = Contrata.objects.all()
    context = {'contratas': contratas,}
    return render(request,'contrata/listar.html',context)
    
def registarAsesorAPI(request):
    if request.method == 'POST':
        data = request.POST, request.FILES
        # print(data[0]['nombre'])
        region = Region.objects.get(id=data[0]['region'])
        asesor = Asesor(
            nombre = data[0]['nombre'],
            tipo_documento =data[0]['tipo_documento'],
            documento = data[0]['documento'],
            telefono = data[0]['telefono'],
            correo = data[0]['correo'],
            funcion = data[0]['funcion'],
            precio = data[0]['precio'],
            region = region,
            foto = data[1]['foto'],
            
            )
        asesor.save()
        
        return redirect('/asesor/registrar/')

def registarRegionAPI(request):
    if request.method == 'POST':
        data = request.POST, request.FILES
        # print(data[0]['nombre'])
        region = Region(
            nombre = data[0]['nombre'],
            
            )
        region.save()
        
        return redirect('/region/registrar/')

def registrarContrataAPI(request,id):
    if request.method=='POST':
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        cliente = Cliente()
        cliente.nombre = body['nombre']
        cliente.apellido = body['apellido']
        cliente.telefono = body['telefono']
        cliente.direccion = body['direccion']
        cliente.save()

        asesor = Asesor.objects.get(id=id)

        contrata = Contrata()
        contrata.asunto = body['asunto']
        contrata.asesor = asesor
        contrata.cliente = cliente
        
        contrata.save()
        
    return HttpResponse(json.dumps("respuesta"), content_type='application/json')

templates/asesor/registrar.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<br>

<div>
    <div class="wrapper">
      <div class="col-1">
        <h3><b>Registrar</b> Asesor</h3>
        <form id="contacts-form" method="post" action="{% url 'main:registrarAsesorAPI' %}" enctype="multipart/form-data">
            {% csrf_token %}
          <fieldset>
            <div class="field">
              <label>Nombre:</label>
              <input type="text" name="nombre" id="id_nombre">
            </div>
            <div class="field">
              <label>Tipo de documento:</label>
              <input type="text" name="tipo_documento" id="id_tipo_documento">
            </div>
            <div class="field">
              <label>Numero de documento:</label>
              <input type="text" name="documento" id="id_documento">
            </div>
            <div class="field">
                <label>Telefono:</label>
                <input type="text" name="telefono" id="id_telefono">
              </div>
              <div class="field">
                <label>Correo:</label>
                <input type="text" name="correo" id="id_correo">
              </div>
            <div class="field">
              <label>Funcion:</label>
              <textarea cols="1" rows="1" name="funcion" id="id_funcion"></textarea>
            </div>
            <div class="field">
                <label>Precio:</label>
                <input type="number" name="precio" id="id_lrecio">
            </div>

            <div class="field">
                <label for="">Region:</label>
                        <select name="region" id="id_region" >
                            <option value="">Seleccione la region...</option>
                            {% for region in regiones %}
                                <option value="{{region.id}}">{{region.nombre}}</option>
                            {% endfor %}
                        </select>
            </div>
            
            <div class="field">
                <label>Foto:</label>
                <input type="file" name="foto" id="id_foto">
            </div>
            
            
    
            <div class="wrapper"><button type="submit" class="link1"><em><b>Registrar</b></em></button></div>
        </fieldset>
        </form>
      </div>
    </div>
</div>


{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CarAdvisory | </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" />
<script src="/static/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<script src="/static/js/cufon-yui.js" type="text/javascript"></script>
<script src="/static/js/cufon-replace.js" type="text/javascript"></script>
<script src="/static/js/Myriad_Pro_400.font.js" type="text/javascript"></script>
<script src="/static/js/Myriad_Pro_600.font.js" type="text/javascript"></script>
<script src="/static/js/NewsGoth_BT_400.font.js" type="text/javascript"></script>
<script src="/static/js/NewsGoth_BT_700.font.js" type="text/javascript"></script>
<script src="/static/js/NewsGoth_Dm_BT_400.font.js" type="text/javascript"></script>
<script src="/static/js/script.js" type="text/javascript"></script>


<!--[if lt IE 7]>
<script type="text/javascript" src="js/ie_png.js"></script>
<script type="text/javascript">ie_png.fix('.png, #header .row-2 ul li a, .extra img, #search-form a, #search-form a em, #login-form .field1 a, #login-form .field1 a em, #login-form .field1 a b');</script>
<link href="css/ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body id="page4">
<!-- START PAGE SOURCE -->
<div id="main">
  <div id="header">
    <div class="row-1">
      <div class="fleft"><a href="#"><img src="/static/images/logo.gif" alt="" /></a></div>
      <div class="fright">
        <ul>
          <li><a href="{% url 'main:registrarAsesor' %}"><img src="/static/images/icon1.gif" alt="" /></a></li>
          <li><a href="{% url 'main:registrarRegion' %}"><img src="/static/images/icon2.gif" alt="" /></a></li>
          <li><a href="{% url 'main:listarContrata' %}"><img src="/static/images/icon3.gif" alt="" /></a></li>
        </ul>
      </div>
    </div>
    <div class="row-2">
      <div class="left">
        <ul>
          <li><a href="{% url 'main:mostrarIndex' %}"><span>Inicio</span></a></li>
          <li><a href="{% url 'main:mostrarNosotros' %}"><span>nosotros</span></a></li>
          <li><a href="{% url 'main:mostrarAsesores' id_region=1 %}"><span>asesores</span></a></li>
          <li><a href="{% url 'main:mostrarContacto' %}"><span>contacto</span></a></li>
          <li class="last"><a href="{% url 'main:mostrarServicios' %}"><span>servicios</span></a></li>
        </ul>
      </div>
    </div>
    <div class="row-3">
      <div class="inside">
        <h2>La velocidad es el origen <b>de las Emociones</b></h2>
        <p>Nosotros lo sabemos, y queremos los mejor para ti!.</p>
        
      </div>
    </div>
    <div class="extra"><img src="/static/images/header-img.png" alt="" /></div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="footer">
    <div class="footer-nav">
      <div class="left">
        <ul>
          
        </ul>
      </div>
    </div>
    <div class="footerlink">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf">Design by <a href="http://www.templatemonster.com/">TemplateMonster</a></p>
      <div style="clear:both;"></div>
    </div>
  </div>
</div>
<script type="text/javascript"> Cufon.now(); </script>
<!-- END PAGE SOURCE -->
</body>
</html>

templates/contrata/listar.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<table>
    <thead>
        <tr>
            <th>Cliente</th>
            <th>Asesor</th>
            <th>Asunto</th>
            <th>Fecha</th>
        </tr>
    </thead>
    <tbody>
        {% for contrata in contratas %}
        <tr>
            <td>{{ contrata.cliente.nombre }} {{ contrata.cliente.apellido }}</td>
            <td>{{ contrata.asesor.nombre }}</td>
            <td>{{ contrata.asunto }}</td>
            <td>{{contrata.fecha|date:"d-m-Y P" }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>

<style>
    
table {
  table-layout: fixed;
  width: 100%;
  border-collapse: collapse;
  border: 3px solid black;
}

thead th:nth-child(1) {
  width: 30%;
}

thead th:nth-child(2) {
  width: 20%;
}

thead th:nth-child(3) {
  width: 15%;
}

thead th:nth-child(4) {
  width: 35%;
}

th, td {
  padding: 20px;
}
html {
  font-family: 'helvetica neue', helvetica, arial, sans-serif;
}

thead th, tfoot th {
  font-family: 'Rock Salt', cursive;
}

th {
  letter-spacing: 2px;
}

td {
  letter-spacing: 1px;
}

tbody td {
  text-align: center;
}

tfoot th {
  text-align: right;
}
</style>
{% endblock %}

templates/main/asesor/asesor.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="box">
    <div class="border-bot">
      <div class="right-bot-corner">
        <div class="left-bot-corner">
          <div class="inner">
            <div class="box1 alt">
              <div class="inner">
                <h4><b>Asesor</b> de Autos</h4>
                <p class="p0"> Sitio web para la busqueda de profesionales en el asesoramiento de autos, servicio post-venta de automobiles, de marcas de prestigio mundial tales como Mercedes-Benz, Freightliner, Western Star, Chrysler, Jeep, Dodge y RAM.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">
        <h3><b>{{asesor.nombre}}</b> </h3>
        <div class="img-box1"><img src="/media/{{asesor.foto}}" width="120" height="100" alt="" />
          <p class="p0">{{asesor.funcion}}</p>
        </div>
        <p>Teléfono: {{asesor.telefono}}</p>
        <p>Correo: {{asesor.correo}}</p>
        <p>Precio: {{asesor.precio}}</p>
        <p>Región: {{asesor.region.nombre}}</p>
        <p> <button onclick="contratarAsesor();" >Contratar Asesor</button> </p>
      </div>

    </div>
  </div>

<script>
var id = '{{asesor.id}}'
function contratarAsesor(){
  document.location = "/pago/"+id+"/"
}
</script>

  {% endblock %}

templates/main/asesores/asesores.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="box">
    <div class="border-bot">
      <div class="right-bot-corner">
        <div class="left-bot-corner">
          <div class="inner">
            <div class="box1 alt">
              <div class="inner">
                <h4><b>NUESTROS</b> ASESORES</h4>
                <p class="p0">Seleccionamos a nuestros asesores para brindar la mayor seguridad en su compra respetando nuestros valores Responsabilidad, honestidad, compromiso y un alto enfoque en el servicio al cliente.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">

        <br>
        <input type="hidden" value="{{oRegion}}" id="id_oregion">
        <label for="">Region:</label>
                <select name="region" id="id_region" class="form-control" >
                    <option value="">Seleccione la region...</option>
                    {% for region in regiones %}
                        <option value="{{region.id}}">{{region.nombre}}</option>
                    {% endfor %}
                </select>
                <button type="button" onclick="buscarAsesores();">Buscar</button>
        <br>

        <h3><b>Asesores</b></h3>
        <ul class="list">
          {% for asesor in asesores %}
          <li><img src="/media/{{asesor.foto}}" alt="" height="100" width="130" /><a href="asesor.html">{{asesor.nombre}}</a><br />
            {{asesor.funcion}} <p></p><a href="/asesor/{{asesor.id}}/" type="button">Ver</a></p></li>
            
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

<script>
window.onload = function() {
  var id = document.getElementById("id_oregion").value;
  console.log("estooo ")
  console.log(id);
  var region = document.getElementById("id_region")
  region.selectedIndex=id;
};

function buscarAsesores(){
  var region = document.getElementById("id_region")
  var id_region = region.options[region.selectedIndex].value
  location.href = "/asesores/"+ id_region +"/";
}
</script>
{% endblock %}

templates/main/contacto/contacto.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="box">
    <div class="border-bot">
      <div class="right-bot-corner">
        <div class="left-bot-corner">
          <div class="inner">
            <div class="box1 alt">
              <div class="inner">
                <h4><b>Contactos</b> </h4>
                <div class="address"><b>Ciudad:</b>05000<br />
                  <b>Dirección:</b>Ciro Alegria<br />
                  <b>Teléfono:</b>+354 5635600<br />
                  <b>Celular:</b>+51 918262097</div>
                <p class="p0 extra-wrap"><b>El equipo de CarAdvisory agradece tu interés.</b><br />
                  Esta área es para que puedas solicitar información adicional y/o específica sobre tu vehículo y/o el plan financiero que quieres para comprarlo. También puedes hacer una cita para visitar nuestras oficinas.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">
        <h3><b>Formulario</b> de Contacto</h3>
        <form id="contacts-form" action="#">
          <fieldset>
            <div class="field">
              <label>Nombre:</label>
              <input type="text" value=""/>
            </div>
            <div class="field">
              <label>Apellido:</label>
              <input type="text" value=""/>
            </div>
            <div class="field">
              <label>E-mail:</label>
              <input type="text" value=""/>
            </div>
            <div class="field">
              <label>Mensaje:</label>
              <textarea cols="1" rows="1"></textarea>
            </div>
            <div class="wrapper"><a href="#" class="link1"><em><b>ENVIAR</b></em></a></div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}

templates/main/index/index.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<ul class="box-list">
    <li>
      <div class="box">
        <div class="border-bot">
          <div class="right-bot-corner">
            <div class="left-bot-corner">
              <div class="inner">
                <div class="box1">
                  <div class="inner">
                    <h4><b>Deportivo</b></h4>
                    <p> Porsche, Mazda, BMW, Mercedes-Benz, Chevrolet, Honda, Ford, Fiat ,etc <a href="#"><img src="images/arrow.gif" alt="" /></a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li class="alt">
      <div class="box">
        <div class="border-bot">
          <div class="right-bot-corner">
            <div class="left-bot-corner">
              <div class="inner">
                <div class="box1">
                  <div class="inner">
                    <h4><b>Todo</b> Terreno</h4>
                    <p>Toyota Land Cruiser, Suzuki Jimny, Land Rover Discovery, BMW X5, Dacia Duster,Fiat Panda Cross 4×4, etc. <a href="#"><img src="images/arrow.gif" alt="" /></a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li class="last">
      <div class="box">
        <div class="border-bot">
          <div class="right-bot-corner">
            <div class="left-bot-corner">
              <div class="inner">
                <div class="box1">
                  <div class="inner">
                    <h4><b>Económico</b> </h4>
                    <p>Tata, Bajaj Qute, Fiat 500, Chery QQ, Maruti, Geely, Dacia Logan, Honda Fit, etc. <a href="#"><img src="images/arrow.gif" alt="" /></a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
  </ul>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">
        <h3><b>Bienvenidos a</b> Car Advisory</h3>
        <p>Sitio web en donde encontraras a los mejores asesores de autos pre-compra al precio de su bolsillo.</p>
        <div class="img-box1"><img src="images/1page-img.jpg" alt="" />
          <p class="p0">Nosotros sabemos lo importante que es elegir bien a la hora de comprar un auto. 
           <a href="#">CarAdvisory </a> Selecciona a los mejores asesores de autos para tu completa seguridad y sin costos excesivos.</p>
        </div>
        <p> <a href="#"></a> .</p>
        <p class="p0"></p>
      </div>
    </div>
  </div>
  {% endblock %}

templates/main/nosotros/nosotros.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="box">
    <div class="border-bot">
      <div class="right-bot-corner">
        <div class="left-bot-corner">
          <div class="inner">
            <div class="box1 alt">
              <div class="inner">
                <h4><b>¿QUIÉNES </b> SOMOS?</h4>
                <p class="p0">Somos una consultoría 100% enfocada a brindar una solución a la necesidad de movilidad de nuestros clientes a través de los mejores asesores, para la busqueda de autos que se encuentren vigentes en el mercado y esté adecuada a su perfil económico.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">
        <h3><b>NUESTRO</b> EQUIPO</h3>
        <ul class="list">
          <li><img src="/static/images/2page-img1.jpg" alt="" /><a href="#">Jose</a><br />
            Administrador.</li>
          <li><img src="/static/images/2page-img2.jpg" alt="" /><a href="#">Juan</a><br />
            Desarrolador</li>
          <li><img src="/static/images/2page-img3.jpg" alt="" /><a href="#">Jean</a><br />
            Analista</li>
          <li><img src="/static/images/2page-img4.jpg" alt="" /><a href="#">Josep</a><br />
            Director</li>
        </ul>
      </div>

    </div>
  </div>

  {% endblock %}

templates/pago/pago.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<br>
<br>
<br>

<div class="box">
    <div class="border-bot">
      <div class="right-bot-corner">
        <div class="left-bot-corner">
          <div class="inner">
            <div class="box1 alt">
              <div class="inner">
                <h4><b>Asesor</b> de Autos</h4>
                <p class="p0"> Sitio web para la busqueda de profesionales en el asesoramiento de autos, servicio post-venta de automobiles, de marcas de prestigio mundial tales como Mercedes-Benz, Freightliner, Western Star, Chrysler, Jeep, Dodge y RAM.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="indent">
    <div class="wrapper">
      <div class="col-1">
        <h3><b>{{asesor.nombre}}</b> </h3>
        <div class="img-box1"><img src="/media/{{asesor.foto}}" width="120" height="100" alt="" />
          <p class="p0">{{asesor.funcion}}</p>
        </div>
        <p>Teléfono: {{asesor.telefono}}</p>
        <p>Correo: {{asesor.correo}}</p>
        <p>Precio: {{asesor.precio}}</p>
        <p>Región: {{asesor.region.nombre}}</p>
      </div>
      <div class="col-2">
        <div class="box2">
          <div class="border-top">
            <div class="left-top-corner">
              <div class="right-top-corner">
                <div class="inner">
                  <h4><b>Contáctenos</h4>
                <form id="form-registro">
                  <fieldset>
                    <div class="field">
                      <label>Nombres:</label><br>
                      <input type="text" name="nombre" id="id_nombre">
                    </div>
                    <br>
                    <div class="field">
                        <label>Apellidos:</label><br>
                        <input type="text" name="apellido" id="id_apellido">
                      </div>
                      <br>
                    <div class="field">
                      <label>Teléfono:</label><br>
                      <input type="text" name="telefono" id="id_telefono">
                    </div>
                    <br>
                    <div class="field">
                      <label>Dirección:</label><br>
                      <input type="text" name="direccion" id="id_direccion">
                    </div>
                    <br>
                    <div class="field">
                      <label>Asunto:</label><br>
                      <textarea cols="30" rows="5" name="asunto" id="id_asunto"></textarea>
                    </div>
                    
                  </fieldset>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <h4>Método de Pago:</h4>
        <div id="paypal-button-container"></div>

      </div>
    </div>
  </div>


<script src="https://www.paypal.com/sdk/js?client-id=ASjUF2dRAxzw0fNC-5vd-URm9UVfRpj4uotiHUQOeo4zLNZdj4hLfOSeGfvpnegyce1MFJ_7HdseaRu8&currency=USD"></script>

<script src="{% static 'js/jquery.cookie.js' %}"></script>

<script>
    function error(){
        alert ("Usted no registro todo sus datos");
    }
    var precio = '{{asesor.precio}}'
    var id = "{{asesor.id}}"

    

    paypal.Buttons({

        // style: {
        //     color: "blue",
        //     shape: "pill",
        //     label: "pay",
        //     height: 30,
        //     width: 50
        // },
        
        createOrder: function(data,actions) {
            var nombre = $("#id_nombre").val();
            var apellido = $("#id_apellido").val();
            var telefono = $("#id_telefono").val();
            var direccion = $("#id_direccion").val();
            var asunto = $("#id_asunto").val(); 

            if(nombre != "" && apellido != "" && telefono !="" && direccion != "" && asunto != ""){
                return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: precio
                    }
                }]
                });
            }else{
                return error();
            }
            
        },

        onApprove: function (data,actions) {
            var nombre = $("#id_nombre").val();
            var apellido = $("#id_apellido").val();
            var telefono = $("#id_telefono").val();
            var direccion = $("#id_direccion").val();
            var asunto = $("#id_asunto").val(); 

            var data = {}
            data.nombre = nombre;
            data.apellido = apellido;
            data.telefono = telefono;
            data.direccion = direccion;
            data.asunto = asunto;

            data = JSON.stringify(data);
            console.log(data)
            autenticarFuncion();
            $.ajax({
                type: "POST",
                url: "/api/contrata/registrar/"+id+"/",
                contentType : 'application/json',
                data: data,
                success: function (data) {
                    $("#form-registro")[0].reset();
                }
            });

            return actions.order.capture().then(function(details) {
                alert("Su transacion ha sido completada como " + details.payer.name.given_name + " nos pondremos en contacto con usted en la brevedad posible!" );
            });
        }

    }).render('#paypal-button-container');


    function autenticarFuncion(){
    var csrftoken = $.cookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

}
</script>
{% endblock %}

templates/region/registrar.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<br>

<div>
    <div class="wrapper">
      <div class="col-1">
        <h3><b>Registrar</b> Región</h3>
        <form id="contacts-form" method="post" action="{% url 'main:registrarRegionAPI' %}" enctype="multipart/form-data">
            {% csrf_token %}
          <fieldset>
            <div class="field">
              <label>Nombre:</label>
              <input type="text" name="nombre" id="id_nombre">
            </div>

            <div class="wrapper"><button type="submit" class="link1"><em><b>REGISTRAR</b></em></button></div>
        </fieldset>
        </form>
      </div>
    </div>
</div>


{% endblock %}